src/Entity/Categories.php
<?php

namespace App\Entity;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoriesRepository::class)]
#[ApiResource]
class Categories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_category = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Produits::class)]
    private Collection $produits;

    public function __toString()
    {
        return $this->nom_category;
    }

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategory(): ?string
    {
        return $this->nom_category;
    }

    public function setNomCategory(string $nom_category): static
    {
        $this->nom_category = $nom_category;

        return $this;
    }

    /**
     * @return Collection<int, Produits>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produits $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setCategory($this);
        }

        return $this;
    }

    public function removeProduit(Produits $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getCategory() === $this) {
                $produit->setCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/Enseignes.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\EnseignesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EnseignesRepository::class)]
#[ApiResource]
class Enseignes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_enseigne = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $nbre_employes = null;

    #[ORM\Column]
    private ?float $chiffre_affaire_annuel_HT = null;
    //! MANY TO MANY avec Produits
    #[ORM\ManyToMany(targetEntity: Produits::class, mappedBy: 'enseignes')]
    private Collection $produits;
    //tableau d'objet qui inclut un tableau en value json_encode

    public function __toString()
    {
        return $this->nom_enseigne;
    }

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEnseigne(): ?string
    {
        return $this->nom_enseigne;
    }

    public function setNomEnseigne(string $nom_enseigne): static
    {
        $this->nom_enseigne = $nom_enseigne;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getNbreEmployes(): ?int
    {
        return $this->nbre_employes;
    }

    public function setNbreEmployes(int $nbre_employes): static
    {
        $this->nbre_employes = $nbre_employes;

        return $this;
    }

    public function getChiffreAffaireAnnuelHT(): ?float
    {
        return $this->chiffre_affaire_annuel_HT;
    }

    public function setChiffreAffaireAnnuelHT(float $chiffre_affaire_annuel_HT): static
    {
        $this->chiffre_affaire_annuel_HT = $chiffre_affaire_annuel_HT;

        return $this;
    }

    /**
     * @return Collection<int, Produits>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produits $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->addEnseigne($this);
        }

        return $this;
    }

    public function removeProduit(Produits $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            $produit->removeEnseigne($this);
        }

        return $this;
    }
}

src/Entity/Produits.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ProduitsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[ORM\Entity(repositoryClass: ProduitsRepository::class)]
#[ApiResource]
//Contrainte pour éviter doublons des noms de produits
// #[UniqueEntity(['nom_produit'], 'Ce nom de produit est indisponible !')]
class Produits
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    //Contrainte sur le nbre de caractères min et max du nom du produit
    //min 2 caractères max 50 
    // la méthode limit est dans le fichier vendor->symfony->contraints->validator->Length.php
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Le nom de votre produit doit être au moins de {{ limit }} caractères',
        maxMessage: 'Le nom de votre produit doit ne peut pas excéder {{ limit }} caractères',
    )]
    private ?string $nom_produit = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_produit = null;

    #[ORM\Column(length: 255)]
    private ?string $image_produit = null;

    #[ORM\Column]
    private ?bool $stock_produit = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_depot_produit = null;

    #[ORM\Column]
    //Contrainte pour interdir des chiffres négatifs pour les prix_produits 
    #[Assert\Positive]
    private ?int $prix_produit = null;
    //! ONE TO ONE avec References
    #[ORM\OneToOne(inversedBy: 'nom_ref_produit', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?References $reference = null;
    
    //! MANY TO MANY  MANY Produits to MANY Enseignes
    #[ORM\ManyToMany(targetEntity: Enseignes::class, inversedBy: 'produits')]
    private Collection $enseignes;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $category = null;

    //! MANY TO ONE  MANY ProduitS TO ONE Users
    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $user = null;

    public function __construct()
    {
        $this->enseignes = new ArrayCollection();
    }
    // todo la propriete de class $reference sera a appellé dans  pour appeller la methode getNumeroReference() methode de la class References.php

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): static
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getDescriptionProduit(): ?string
    {
        return $this->description_produit;
    }

    public function setDescriptionProduit(string $description_produit): static
    {
        $this->description_produit = $description_produit;

        return $this;
    }

    public function getImageProduit(): ?string
    {
        return $this->image_produit;
    }

    public function setImageProduit(string $image_produit): static
    {
        $this->image_produit = $image_produit;

        return $this;
    }

    public function isStockProduit(): ?bool
    {
        return $this->stock_produit;
    }

    public function setStockProduit(bool $stock_produit): static
    {
        $this->stock_produit = $stock_produit;

        return $this;
    }

    public function getDateDepotProduit(): ?\DateTimeInterface
    {
        return $this->date_depot_produit;
    }

    public function setDateDepotProduit(\DateTimeInterface $date_depot_produit): static
    {
        $this->date_depot_produit = $date_depot_produit;

        return $this;
    }

    public function getPrixProduit(): ?int
    {
        return $this->prix_produit;
    }

    public function setPrixProduit(int $prix_produit): static
    {
        $this->prix_produit = $prix_produit;

        return $this;
    }

    public function getReference(): ?References
    {
        return $this->reference;
    }

    public function setReference(References $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * @return Collection<int, Enseignes>
     */
    public function getEnseignes(): Collection
    {
        return $this->enseignes;
    }

    public function addEnseigne(Enseignes $enseigne): static
    {
        if (!$this->enseignes->contains($enseigne)) {
            $this->enseignes->add($enseigne);
        }

        return $this;
    }

    public function removeEnseigne(Enseignes $enseigne): static
    {
        $this->enseignes->removeElement($enseigne);

        return $this;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/References.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ReferencesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReferencesRepository::class)]
#[ORM\Table(name: '`references`')]
#[ApiResource]
class References
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $numero_reference = null;

    //! ONE TO ONE avec Produits
    #[ORM\OneToOne(mappedBy: 'reference', cascade: ['persist', 'remove'])]
    private ?Produits $nom_ref_produit = null;

    public function __toString()
    {
        return $this->numero_reference;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroReference(): ?int
    {
        return $this->numero_reference;
    }

    public function setNumeroReference(int $numero_reference): static
    {
        $this->numero_reference = $numero_reference;

        return $this;
    }

    public function getNomRefProduit(): ?Produits
    {
        return $this->nom_ref_produit;
    }

    public function setNomRefProduit(Produits $nom_ref_produit): static
    {
        // set the owning side of the relation if necessary
        if ($nom_ref_produit->getReference() !== $this) {
            $nom_ref_produit->setReference($this);
        }

        $this->nom_ref_produit = $nom_ref_produit;

        return $this;
    }
}

src/Form/ProduitsType.php
<?php

namespace App\Form;

use App\Entity\Categories;
use App\Entity\Enseignes;
use App\Entity\Produits;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_produit', TextType::class)
            ->add('description_produit', TextareaType::class)
            ->add('image_produit', FileType::class, array(
                'label' => 'Image du produit',
                'required' => false,
                'data_class' => null,
                'empty_data' => 'ce produit n\'a pas d\'image',
            ))
            ->add('stock_produit', CheckboxType::class)
            ->add('date_depot_produit', DateType::class, array(
                'widget' => 'single_text',
            ))
            ->add('prix_produit', NumberType::class, [
                'label' => 'Prix en €uro',
            ])
            ->add('reference', ReferencesType::class, [
                'required' => true,
            ])
            ->add('enseignes', EntityType::class, [
                'class' => Enseignes::class,
                'choice_label'=> 'nomEnseigne',
                'label'=> 'Sélectionner une ou plusieurs enseigne(s)',
                'multiple' => true,
            ])
            ->add('category', EntityType::class, array(
                'class' => Categories::class,
                'choice_label'=> 'nomCategory',
                'required' => true,
            ))
            ->add('user', EntityType::class, array(
                'class' => Users::class,
                'disabled' => true,
            ));
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produits::class,
            'constraints' => array(new UniqueEntity(['fields' => 'nom_produit'], 'Ce nom de produit est indisponible !'))
        ]);
    }
}

//todo la propriete de class $reference sera a appellé dans  pour appeller la methode getNumeroReference() methode de la class References.php
//todo ReferencesType gère à la fois le type de l'input et imbrique le formulaire ReferencesType dans le formulaire ProduitsType
//todo ainsi quand on voudra ajouter un produit le form de ReferenceType sera inclus inside

templates/produits/_delete_form.html.twig
<form method="post" action="{{ path('app_produits_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produits/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }} #}

{{ form_start(form) }}
{% form_theme form 'tailwind_2_layout.html.twig' %}

    <div class="d-flex justify-content-between w-50 mx-auto ">
        {{ form_row(form.nom_produit,{'attr':{'class': 'form-control'}}) }}
        {{ form_row(form.prix_produit,{'attr':{'class': 'form-control'}}) }}
    </div>

    <div class="d-flex flex-column justify-content-md-center align-items-left w-50 mx-auto mt-3">
        {{ form_row(form.description_produit,{'attr':{'class': 'form-control mb-3'}}) }}
        {{ form_row(form.image_produit,{'attr':{'class': 'form-control mb-3'}}) }}
        {{ form_row(form.stock_produit,{'attr': {'class': 'form-check-input me-3 mb-3'}}) }}
        {{ form_row(form.date_depot_produit,{'attr':{'class': 'form-control mb-3'}}) }}
        {{ form_row(form.enseignes,{'attr':{'class': 'form-control mb-3'}}) }}
        {{ form_row(form.category,{'attr':{'class': 'form-control mb-3'}}) }}
        {{ form_row(form.user,{'attr':{'class': 'form-control mb-3'}}) }}
        {{ form_row(form.reference,{'attr':{'class': 'form-control mb-3'}}) }}
    </div>

    <div class="d-flex justify-content-center ">
    <button class="btn btn-info text-white">{{ button_label|default('Ajouter') }}</button>
    </div>

{{ form_end(form) }}

templates/produits/cardProduit.html.twig
{% block body %}
</body>
<section class="d-flex flex-column align-items-center ">
			<div class="card" style="width: 25rem;">
				<img src="{{ asset('img/' ~ nomProduitRef.imageProduit) }}" class="card-img-top" alt="...">
				<div class="card-body">
					<h4 class="card-title">{{ nomProduitRef.nomProduit }}</h4>
					<p class="card-text">Description:
						{{ nomProduitRef.descriptionProduit }}</p>
					<p class="card-text">Réf.
						<b>{{ nomProduitRef.reference.numeroReference }}</b>&nbsp&nbsp
						Cat.
					<b>{{nomProduitRef.category.nomCategory}}</b>
					</p>
					
				</div>
				<ul class="list-group list-group-flush">

					<li class="list-group-item">Prix:
						{{ nomProduitRef.prixProduit }} €</li>
					<li class="list-group-item">En stock:
						{{ nomProduitRef.stockProduit ? 'disponible' : 'rupture de stock' }}</li>
					<li class="list-group-item">Date de dépôt:
						{{ nomProduitRef.dateDepotProduit ? nomProduitRef.dateDepotProduit|date('d/m/Y') : '' }}</li>

					{# {% if nomProduitRef.stockProduit == 'disponible' %}
					<ul class="list-group list-group-flush mb-2 " style="padding-left: 1rem">Enseigne(s) :

							<li class="list-group-item pt-0 pb-0 ms-5"> - {{ enseignes.nomEnseigne}}</li>

					{% endif %} #}
					</ul>
				</ul>
				{% if app.user %}
					<div class="card-body">
						<a href="{{ path('app_produits_show', {'id': nomProduitRef.id}) }}" class="card-link">Fiche produit</a>
						<a href="{{ path('app_produits_edit', {'id': nomProduitRef.id}) }}" class="card-link">Modifier
						</a>
					</div>
			</div>
		</section><br>
	{% else %}
		<tr>
			<td colspan="8">no records found</td>
		</tr>
{% endif %}

	{% if app.user %}
		<div class="d-flex col-1 mx-auto mb-3">
			<a class="btn btn-success" href="{{ path('app_produits_new') }}">Ajouter un produit</a>
		</div>
	{% endif %}

{% endblock %}

templates/produits/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produits{% endblock %}

{% block body %}
    <h1>Edit Produits</h1>

    {{ include('produits/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_produits_index') }}">back to list</a>

    {{ include('produits/_delete_form.html.twig') }}
{% endblock %}

templates/produits/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits
{% endblock %}

{% block body %}

	<section class="d-flex flex-column align-items-center ">
		<h2>Produit du mois</h2>
		<div class="card" style="width: 18rem;">
			<img src="{{ asset('img/' ~ produitVedette.imageProduit) }}" class="card-img-top" alt="...">
			<div class="card-body">
				<p class="card-text">
					<b>{{ produitVedette.nomProduit }}</b>
					<span>{{ produitVedette.prixProduit }}
						€</span>
				</p>
				<p class="card-text">Réf.
					{{ produitVedette.reference.numeroReference }}&nbsp&nbsp Cat.
					{{ produitVedette.category.nomCategory }}</p>
			</div>
			<a class="btn btn-outline-success" href="{{ path('app_produits_show', {'id': produitVedette.id}) }}">Voir le produit</a>
		</div>
	</section>

	<hr>
	
		<div
			class="d-flex justify-content-center col-4 mx-auto  ">
			{# <input class="form-control searchbar m-4" type="search" name="ref" placeholder="Search" aria-label="Search"> #}
			<a href="{{path('app_search_index')}}" class="btn btn-success m-3">Rechercher par nom, référence, categorie, distributeur</a><br>
		</div>

		{# ! All products with pagination #}
		<div class="d-flex justify-content-center mx-auto gap-3 mb-3">
			{# total items count #}
			<h4 class="text-center">Tous les produits ( x
				{{ pagination.getTotalItemCount }})</h4>
			{# display navigation #}
			<h5>{{ knp_pagination_render(pagination) }}</h5>
		</div>

		<section class="d-flex justify-content-center mx-auto gap-3 ">
			{% for produit in pagination %}
			{# ! All products with pagination #}
				{# {% for produit in produits %} #}
				{# <section class="d-flex flex-column align-items-center "> #}
					<div class="card" style="width: 25rem;"> <img src="{{ asset('img/' ~ produit.imageProduit) }}" class="card-img-top " alt="...">
					<div class="card-body">
						<h4 class="card-title">{{ produit.nomProduit }}</h4>
						<p class="card-text">Description:
							{{ produit.descriptionProduit }}</p>
						<p class="card-text">Réf.
							<b>{{ produit.reference.numeroReference }}</b>&nbsp&nbsp Cat.<b>{{produit.category.nomCategory}}</b>
						</p>

					</div>
					<ul class="list-group list-group-flush">
						<li class="list-group-item">Prix:
							{{ produit.prixProduit }}
							€</li>
						<li class="list-group-item">En stock:
							{{ produit.stockProduit ? 'disponible' : 'rupture de stock' }}</li>
						<li class="list-group-item">Date de dépôt:
							{{ produit.dateDepotProduit ? produit.dateDepotProduit|date('d/m/Y') : '' }}</li>

						{% if produit.stockProduit == 'disponible' %}
							<ul class="list-group list-group-flush mb-2 " style="padding-left: 1rem">Enseigne(s) :
								{% for enseignes in produit.enseignes %}
									<li class="list-group-item pt-0 pb-0 ms-5">
										-{{ enseignes.nomEnseigne}}
										</li>
								{% endfor %}
							{% endif %}
						</ul>
					</ul>
					{% if app.user %}

						<div></div>
						<a class="btn btn-outline-success" href="{{ path('app_produits_show', {'id': produit.id}) }}">Voir le produit</a>

						{# <a href="{{ path('app_produits_show', {'id': produit.id}) }}" class="card-link">Fiche produit</a> #}
						{# <a href="{{ path('app_produits_edit', {'id': produit.id}) }}" class="card-link">Modifier
																												</a> #}
					</div>

				{% endif %}
			</div>
			<br>
		{% else %}
			<tr>
				<td colspan="8">no records found</td>
			</tr>
		{% endfor %}
	</section>
	{% if app.user %}
		<div
			class="d-flex col-1 mx-auto mb-3">{# <a class="btn btn-success" href="{{ path('app_produits_new') }}">Ajouter un produit</a> #}
		</div>
	{% endif %}
{% endblock %}

templates/produits/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produits{% endblock %}

{% block body %}
    <h1>Create new Produits</h1>

    {{ include('produits/_form.html.twig') }}

    <a href="{{ path('app_produits_index') }}">back to list</a>
{% endblock %}

templates/produits/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits{% endblock %}

{% block body %}
    <h1>Produits</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Nom_produit</th>
                <td>{{ produit.nomProduit }}</td>
            </tr>
            <tr>
                <th>Description_produit</th>
                <td>{{ produit.descriptionProduit }}</td>
            </tr>
            <tr>
                <th>Image_produit</th>
                <td>{{ produit.imageProduit }}</td>
            </tr>
            <tr>
                <th>Stock_produit</th>
                <td>{{ produit.stockProduit ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Date_depot_produit</th>
                <td>{{ produit.dateDepotProduit ? produit.dateDepotProduit|date('Y-m-d H:i:s') : '' }}</td>
            </tr>

            <tr>
                <th>Référence</th>
                <td>{{ produit.reference.numeroReference }}</td>
            </tr>
            <tr>
                <th>Catégorie</th>
                <td>{{produit.category.nomCategory}}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('app_produits_index') }}">back to list</a>
    {# <a href="{{ path('app_produits_edit', {'id': produit.id}) }}" >edit</a> #}
    
    {# {{ include('produits/_delete_form.html.twig') }} #}
{% endblock %}

templates/produits/tableauBordUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits
{% endblock %}
{% block navbarUserProduits %}
	<li>
		<a class="dropdown-item" href="{{path('app_produits_new')}}">Ajouter un produit</a>
	</li>

{% endblock %}
{% block body %}
	<div class="mt-3 text center"></div>
	<h4 class="title m-auto ls-3 has-text-danger" style="width: 100%; background-color: #1c1917; color: white; padding: 20px">Tableau de bord:
		{{app.user.email}}</h4>
</div>


<section class="d-flex justify-content-center gap-5 align-items-center mt-3 mb-0">
	{% for produit in userProduits %}
		<div class="card" style="width: 23rem;">
			<img src="{{ asset('img/' ~ produit.imageProduit) }}" class="card-img-top" alt="..." width="25%" height="280px">
			<div class="card-body">
				<h4 class="card-title">{{ produit.nomProduit }}</h4>
				<p class="card-text">Description:
					{{ produit.descriptionProduit }}</p>
				<p class="card-text">Réf.
					<b>{{ produit.reference.numeroReference }}</b>&nbsp&nbsp Cat.
					<b>{{produit.category.nomCategory}}</b>
				</p>
			</div>

			<ul class="list-group list-group-flush">
				<li class="list-group-item">Prix:
					{{ produit.prixProduit }}
					€</li>

				<li class="list-group-item">En stock:
					{{ produit.stockProduit ? 'disponible' : 'rupture de stock' }}</li>
				<li class="list-group-item">Date de dépôt:
					{{ produit.dateDepotProduit ? produit.dateDepotProduit|date('d/m/Y') : '' }}</li>

				{% if produit.stockProduit == 'disponible' %}
					<ul class="list-group list-group-flush mb-2 " style="padding-left: 1rem">Enseigne(s) :
						{% for enseignes in produit.enseignes %}
							<li class="list-group-item pt-0 pb-0 ms-5">-
								{{ enseignes.nomEnseigne}}</li>
						{% endfor %}
					</ul>
				{% endif %}
			</ul>

			<div class="card-body">
				<a href="{{ path('app_produits_show', {'id': produit.id}) }}" class="card-link">Fiche produit</a>
				<a href="{{ path('app_produits_edit', {'id': produit.id}) }}" class="card-link">Modifier</a>
			</div>
		</div>
	{% endfor %}
</section>


{# <tr>
<td colspan="8">no records found</td>
</tr> #}
<div class="d-flex col-2 mx-auto mb-3 mt-3">
	<a class="btn btn-outline-success" href="{{ path('app_produits_new') }}">Ajouter un produit</a>
</div>{% endblock %}

templates/produits/test.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits
{% endblock %}

{% block body %}
<input type="text" value="" placeholder="nom du produit">

{% endblock %}