src/Entity/Categories.php
<?php

namespace App\Entity;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoriesRepository::class)]
#[ApiResource]
class Categories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_category = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Produits::class)]
    private Collection $produits;

    public function __toString()
    {
        return $this->nom_category;
    }

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategory(): ?string
    {
        return $this->nom_category;
    }

    public function setNomCategory(string $nom_category): static
    {
        $this->nom_category = $nom_category;

        return $this;
    }

    /**
     * @return Collection<int, Produits>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produits $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setCategory($this);
        }

        return $this;
    }

    public function removeProduit(Produits $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getCategory() === $this) {
                $produit->setCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/Enseignes.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\EnseignesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EnseignesRepository::class)]
#[ApiResource]
class Enseignes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_enseigne = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $nbre_employes = null;

    #[ORM\Column]
    private ?float $chiffre_affaire_annuel_HT = null;
    //! MANY TO MANY avec Produits
    #[ORM\ManyToMany(targetEntity: Produits::class, mappedBy: 'enseignes')]
    private Collection $produits;
    //tableau d'objet qui inclut un tableau en value json_encode

    public function __toString()
    {
        return $this->nom_enseigne;
    }

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEnseigne(): ?string
    {
        return $this->nom_enseigne;
    }

    public function setNomEnseigne(string $nom_enseigne): static
    {
        $this->nom_enseigne = $nom_enseigne;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getNbreEmployes(): ?int
    {
        return $this->nbre_employes;
    }

    public function setNbreEmployes(int $nbre_employes): static
    {
        $this->nbre_employes = $nbre_employes;

        return $this;
    }

    public function getChiffreAffaireAnnuelHT(): ?float
    {
        return $this->chiffre_affaire_annuel_HT;
    }

    public function setChiffreAffaireAnnuelHT(float $chiffre_affaire_annuel_HT): static
    {
        $this->chiffre_affaire_annuel_HT = $chiffre_affaire_annuel_HT;

        return $this;
    }

    /**
     * @return Collection<int, Produits>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produits $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->addEnseigne($this);
        }

        return $this;
    }

    public function removeProduit(Produits $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            $produit->removeEnseigne($this);
        }

        return $this;
    }
}

src/Entity/Produits.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ProduitsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[ORM\Entity(repositoryClass: ProduitsRepository::class)]
#[ApiResource]
//Contrainte pour éviter doublons des noms de produits
// #[UniqueEntity(['nom_produit'], 'Ce nom de produit est indisponible !')]
class Produits
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    //Contrainte sur le nbre de caractères min et max du nom du produit
    //min 2 caractères max 50 
    // la méthode limit est dans le fichier vendor->symfony->contraints->validator->Length.php
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Le nom de votre produit doit être au moins de {{ limit }} caractères',
        maxMessage: 'Le nom de votre produit doit ne peut pas excéder {{ limit }} caractères',
    )]
    private ?string $nom_produit = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_produit = null;

    #[ORM\Column(length: 255)]
    private ?string $image_produit = null;

    #[ORM\Column]
    private ?bool $stock_produit = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_depot_produit = null;

    #[ORM\Column]
    //Contrainte pour interdir des chiffres négatifs pour les prix_produits 
    #[Assert\Positive]
    private ?int $prix_produit = null;
    //! ONE TO ONE avec References
    #[ORM\OneToOne(inversedBy: 'nom_ref_produit', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?References $reference = null;
    
    //! MANY TO MANY  MANY Produits to MANY Enseignes
    #[ORM\ManyToMany(targetEntity: Enseignes::class, inversedBy: 'produits')]
    private Collection $enseignes;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $category = null;

    //! MANY TO ONE  MANY ProduitS TO ONE Users
    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $user = null;

    public function __construct()
    {
        $this->enseignes = new ArrayCollection();
    }
    // todo la propriete de class $reference sera a appellé dans  pour appeller la methode getNumeroReference() methode de la class References.php

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): static
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getDescriptionProduit(): ?string
    {
        return $this->description_produit;
    }

    public function setDescriptionProduit(string $description_produit): static
    {
        $this->description_produit = $description_produit;

        return $this;
    }

    public function getImageProduit(): ?string
    {
        return $this->image_produit;
    }

    public function setImageProduit(string $image_produit): static
    {
        $this->image_produit = $image_produit;

        return $this;
    }

    public function isStockProduit(): ?bool
    {
        return $this->stock_produit;
    }

    public function setStockProduit(bool $stock_produit): static
    {
        $this->stock_produit = $stock_produit;

        return $this;
    }

    public function getDateDepotProduit(): ?\DateTimeInterface
    {
        return $this->date_depot_produit;
    }

    public function setDateDepotProduit(\DateTimeInterface $date_depot_produit): static
    {
        $this->date_depot_produit = $date_depot_produit;

        return $this;
    }

    public function getPrixProduit(): ?int
    {
        return $this->prix_produit;
    }

    public function setPrixProduit(int $prix_produit): static
    {
        $this->prix_produit = $prix_produit;

        return $this;
    }

    public function getReference(): ?References
    {
        return $this->reference;
    }

    public function setReference(References $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * @return Collection<int, Enseignes>
     */
    public function getEnseignes(): Collection
    {
        return $this->enseignes;
    }

    public function addEnseigne(Enseignes $enseigne): static
    {
        if (!$this->enseignes->contains($enseigne)) {
            $this->enseignes->add($enseigne);
        }

        return $this;
    }

    public function removeEnseigne(Enseignes $enseigne): static
    {
        $this->enseignes->removeElement($enseigne);

        return $this;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/References.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ReferencesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReferencesRepository::class)]
#[ORM\Table(name: '`references`')]
#[ApiResource]
class References
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $numero_reference = null;

    //! ONE TO ONE avec Produits
    #[ORM\OneToOne(mappedBy: 'reference', cascade: ['persist', 'remove'])]
    private ?Produits $nom_ref_produit = null;

    public function __toString()
    {
        return $this->numero_reference;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroReference(): ?int
    {
        return $this->numero_reference;
    }

    public function setNumeroReference(int $numero_reference): static
    {
        $this->numero_reference = $numero_reference;

        return $this;
    }

    public function getNomRefProduit(): ?Produits
    {
        return $this->nom_ref_produit;
    }

    public function setNomRefProduit(Produits $nom_ref_produit): static
    {
        // set the owning side of the relation if necessary
        if ($nom_ref_produit->getReference() !== $this) {
            $nom_ref_produit->setReference($this);
        }

        $this->nom_ref_produit = $nom_ref_produit;

        return $this;
    }
}

src/Controller/SearchController.php
<?php

namespace App\Controller;

use App\Entity\Categories;
use App\Entity\Enseignes;
use App\Entity\Produits;
use App\Form\SearchBarType;
use App\Form\SelectCatType;
use App\Form\SelectRefType;
use App\Repository\CategoriesRepository;
use App\Repository\EnseignesRepository;
use App\Repository\ProduitsRepository;
use App\Repository\ReferencesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/search')]
class SearchController extends AbstractController
{
    #[Route('/', name: 'app_search_index', methods: ['GET', 'POST'])]
    public function index(ProduitsRepository $produitsRepository, Request $request, ReferencesRepository $referencesRepository, CategoriesRepository $categoriesRepository, EnseignesRepository $enseignesRepository): Response
    {
        $produits = new Produits();
        $form_nom = $this->createForm(SearchBarType::class, $produits);
        $form_nom->handleRequest($request);

        $form_ref = $this->createForm(SelectRefType::class, $produits);
        $form_ref->handleRequest($request);

        $form_cat = $this->createForm(SelectCatType::class, $produits);
        $form_cat->handleRequest($request);
        $resultat_search_cat = [];
        $resultat_search= [];


        if ($form_nom->isSubmitted() && $form_nom->isValid()) {
            $mot = $form_nom->get('nom_produit');
            // dd($mot);
            // dd($ref);// -viewData:"" -name:"" nom de colonne de produits de la key du form SearchBarType ex.// viewData:"3"
            // dd( $ref->getViewData());//retourne "3" l'id 
            // dd($ref->getName());// retourne "reference" nom de colonne et de la key du form SearchBarType
            $mot = $form_nom->get('nom_produit')->getData();
            // dd($form_nom->get('nom_produit')->getName());//nom du produit ex. ordinateur
            //todo = $mot= <input> $_POST['nom_produit'](key=>value)-> value
            $resultat_search = $produitsRepository->searchProduitByNom($mot);
            //dd($resultat_search);//renvoie un [];
            if (count($resultat_search) == 0) {
                $resultat_search = "null";
            }
        }

        if ($form_ref->isSubmitted() && $form_ref->isValid()) {
            $ref = $form_ref->get('reference');
            // dd($ref);// -viewData:"" -name:"" nom de colonne de produits de la key du form SearchBarType ex.// viewData:"3"
            // dd( $ref->getViewData());//retourne "3" l'id 
            // dd($ref->getName());// retourne "reference" nom de colonne et de la key du form SearchBarType
            $ref = $form_ref->get('reference')->getViewData();
            $resultat_search = [$produitsRepository->findOneBy(array('reference' => $ref))];
            // dd($resultat_search);
        }

        

        if ($form_cat->isSubmitted() && $form_cat->isValid()) {
            $cat = $form_cat->get('category');
            // dd($cat);//
            // dd($cat->getViewData());
            $cat = $form_cat->get('category')->getViewData();
            $resultat_search= $produitsRepository->searchProduitByCat($cat);
            // dd($resultat_search);
        }

        return $this->render('search/index.html.twig', [
            'references' => $referencesRepository->findAll(),
            'categories' => $categoriesRepository->findAll(),
            'enseignes' => $enseignesRepository->findAll(),
            'form' => $form_nom->createView(),
            'form_ref' => $form_ref->createView(),
            'form_cat' => $form_cat->createView(),
            'resultats' => $resultat_search,
           ]);
    }

    #[Route('/{id}', name: 'app_search_byRef', methods: ['GET'])]
    public function search(Request $request, ProduitsRepository $produitsRepository): Response
    {
        //! Récupérer la valeur de l'attribut 'id' depuis l'objet Request
        //! L'attribut $request->attributes est un objet de type AttributeBag, qui est essentiellement un conteneur de données associatives. Dans Symfony, les attributs sont utilisés pour stocker des informations supplémentaires sur une requête.
        $attribut = $request->attributes->get('id');

        //! Appeller la method findOneBy du repository et lui passer un array('champ de colonne FK sans _id ' => $variable qui stocke la valeur de l'attribut)
        $nomProduit = $produitsRepository->findOneBy(array('reference' => $attribut));
        //! return l'entity Produits 
        //retourner la vue
        return $this->render('search/findByRef.html.twig', array(
            "attribut" => $attribut,
            "nomProduit" => $nomProduit,
        ));
    }

    #[Route('/categorie/{id}', name: 'app_search_byCat', methods: ['GET'])]
    public function searchCat(Categories $categories): Response
    {
        //! Appeller la method getProduits de l'entity Categories.php
        $nomsProduits = $categories->getProduits();
        //! return l'entity Produits 
        //retourner la vue
        return $this->render('search/findByCat.html.twig', array(
            "categories" => $categories,
            "nomsProduits" => $nomsProduits,
        ));
    }

    #[Route('/shop/{id}', name: 'app_search_by_shop', methods: ['GET'])]
    public function searchEns(Enseignes $enseignes): Response
    {
        //! Appeller la method getProduits de l'entity Categories.php
        $nomsProduits = $enseignes->getProduits();
        //! return l'entity Produits 
        //retourner la vue
        return $this->render('search/findByShop.html.twig', array(
            "enseignes" => $enseignes,
            "nomsProduits" => $nomsProduits,
        ));
    }

    //stock dans une variable une instance de l’entité Produits
    //créé le formulaire
    //le formulaire qui est inspecté via la méthode handleRequest()
    //créé un tableau vide qui va stocker les resultats
    //recupere récupère input. Value avec la méthode getData().     
    //getData() est stocké dans la variable $mot



}

templates/search/cardProduit.html.twig
{% block body %}
</body>
<section class="d-flex flex-column align-items-center ">
			<div class="card" style="width: 25rem;">
				<img src="{{ asset('img/' ~ nomProduit.imageProduit) }}" class="card-img-top" alt="...">
				<div class="card-body">
					<h4 class="card-title">{{ nomProduit.nomProduit }}</h4>
					<p class="card-text">Description:
						{{ nomProduit.descriptionProduit }}</p>
					<p class="card-text">Réf.
						<b>{{ nomProduit.reference.numeroReference }}</b>&nbsp&nbsp
						Cat.
					<b>{{nomProduit.category.nomCategory}}</b>
					</p>
					
				</div>
				<ul class="list-group list-group-flush">

					<li class="list-group-item">Prix:
						{{ nomProduit.prixProduit }} €</li>
					<li class="list-group-item">En stock:
						{{ nomProduit.stockProduit ? 'disponible' : 'rupture de stock' }}</li>
					<li class="list-group-item">Date de dépôt:
						{{ nomProduit.dateDepotProduit ? nomProduit.dateDepotProduit|date('d/m/Y') : '' }}</li>

					{# {% if nomProduit.stockProduit == 'disponible' %}
					<ul class="list-group list-group-flush mb-2 " style="padding-left: 1rem">Enseigne(s) :

							<li class="list-group-item pt-0 pb-0 ms-5"> - {{ enseignes.nomEnseigne}}</li>

					{% endif %} #}
					</ul>
				</ul>
				{% if app.user %}
					<div class="card-body">
						<a href="{{ path('app_produits_show', {'id': nomProduit.id}) }}" class="card-link">Fiche produit</a>
						<a href="{{ path('app_produits_edit', {'id': nomProduit.id}) }}" class="card-link">Modifier
						</a>
					</div>
			</div>
		</section><br>
	{% else %}
		<tr>
			<td colspan="8">no records found</td>
		</tr>
{% endif %}

	{% if app.user %}
		<div class="d-flex col-1 mx-auto mb-3">
			<a class="btn btn-success" href="{{ path('app_produits_new') }}">Ajouter un produit</a>
		</div>
	{% endif %}

{% endblock %}

templates/search/cardProduitCat.html.twig
{% block body %}
</body>
{% for nomProduit in nomsProduits %}
<section class="d-flex justify-content-around align-items-center ">
			<div class="card" style="width: 25rem;">
				<img src="{{ asset('img/' ~ nomProduit.imageProduit) }}" class="card-img-top" alt="...">
				<div class="card-body">
					<h4 class="card-title">{{ nomProduit.nomProduit }}</h4>
					<p class="card-text">Description:
						{{ nomProduit.descriptionProduit }}</p>
					<p class="card-text">Réf.
						<b>{{ nomProduit.reference.numeroReference }}</b>&nbsp&nbsp
						Cat.
					<b>{{nomProduit.category.nomCategory}}</b>
					</p>
					
				</div>
				<ul class="list-group list-group-flush">

					<li class="list-group-item">Prix:
						{{ nomProduit.prixProduit }} €</li>
					<li class="list-group-item">En stock:
						{{ nomProduit.stockProduit ? 'disponible' : 'rupture de stock' }}</li>
					<li class="list-group-item">Date de dépôt:
						{{ nomProduit.dateDepotProduit ? nomProduit.dateDepotProduit|date('d/m/Y') : '' }}</li>

					{# {% if nomProduit.stockProduit == 'disponible' %}
					<ul class="list-group list-group-flush mb-2 " style="padding-left: 1rem">Enseigne(s) :

						{% for enseignes in produit.enseignes %}
							<li class="list-group-item pt-0 pb-0 ms-5"> - {{ enseignes.nomEnseigne}}</li>
						{% endfor %}

					{% endif %} #}
					</ul>
				</ul>
				{% if app.user %}
					<div class="card-body">
						<a href="{{ path('app_produits_show', {'id': nomProduit.id}) }}" class="card-link">Fiche produit</a>
						<a href="{{ path('app_produits_edit', {'id': nomProduit.id}) }}" class="card-link">Modifier
						</a>
					</div>
			</div>
		</section><br>
	{% else %}
		<tr>
			<td colspan="8">no records found</td>
		</tr>
{% endif %}
{% endfor %}
	{% if app.user %}
		<div class="d-flex col-1 mx-auto mb-3">
			<a class="btn btn-success" href="{{ path('app_produits_new') }}">Ajouter un produit</a>
		</div>
	{% endif %}
	

{% endblock %}

templates/search/cardProduitEnseigne.html.twig
{% block body %}
</body>
{% for nomProduit in nomsProduits %}
<section class="d-flex justify-content-around align-items-center ">
			<div class="card" style="width: 25rem;">
				<img src="{{ asset('img/' ~ nomProduit.imageProduit) }}" class="card-img-top" alt="...">
				<div class="card-body">
					<h4 class="card-title">{{ nomProduit.nomProduit }}</h4>
					<p class="card-text">Description:
						{{ nomProduit.descriptionProduit }}</p>
					<p class="card-text">Réf.
						<b>{{ nomProduit.reference.numeroReference }}</b>&nbsp&nbsp
						Cat.
					<b>{{nomProduit.category.nomCategory}}</b>
					</p>
					
				</div>
				<ul class="list-group list-group-flush">

					<li class="list-group-item">Prix:
						{{ nomProduit.prixProduit }} €</li>
					<li class="list-group-item">En stock:
						{{ nomProduit.stockProduit ? 'disponible' : 'rupture de stock' }}</li>
					<li class="list-group-item">Date de dépôt:
						{{ nomProduit.dateDepotProduit ? nomProduit.dateDepotProduit|date('d/m/Y') : '' }}</li>

					{% if nomProduit.stockProduit == 'disponible' %}
					<ul class="list-group list-group-flush mb-2 " style="padding-left: 1rem">Enseigne(s) :

							<li class="list-group-item pt-0 pb-0 ms-5"> - {{ enseignes.nomEnseigne}}</li>

					{% endif %}
					</ul>
				</ul>
				{% if app.user %}
					<div class="card-body">
						<a href="{{ path('app_produits_show', {'id': nomProduit.id}) }}" class="card-link">Fiche produit</a>
						<a href="{{ path('app_produits_edit', {'id': nomProduit.id}) }}" class="card-link">Modifier
						</a>
					</div>
			</div>
		</section><br>
	{% else %}
		<tr>
			<td colspan="8">no records found</td>
		</tr>
{% endif %}
{% endfor %}
	{% if app.user %}
		<div class="d-flex col-1 mx-auto mb-3">
			<a class="btn btn-success" href="{{ path('app_produits_new') }}">Ajouter un produit</a>
		</div>
	{% endif %}
	

{% endblock %}

templates/search/findByCat.html.twig
{% extends 'base.html.twig' %}

{% block title %}produitByCat Found !
{% endblock %}

{% block body %}

<h2>Le(s) produit(s) de cette catégorie :</h2>
  {% include 'search/cardProduitCat.html.twig' %}

{% endblock %}

templates/search/findByRef.html.twig
{% extends 'base.html.twig' %}

{% block title %}produitByRef Found !
{% endblock %}

{% block body %}

<h2>Le produit portant cette référence :</h2>
{# <p>id de la référence: {{attribut}} </p> #}
{# <p>nom produit de la reference: {{nomProduitRef.nomProduit}}</p> #}
 {% include 'search/cardProduit.html.twig' %}

{% endblock %}

templates/search/findByShop.html.twig
{% extends 'base.html.twig' %}

{% block title %}produitByCat Found !
{% endblock %}

{% block body %}

<h2>Le(s) produit(s) de cette enseigne :</h2>
  {% include 'search/cardProduitEnseigne.html.twig' %}

{% endblock %}

templates/search/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search!
{% endblock %}

{% block body %}

	<section class="d-flex justify-content-around align-items-baseline mt-5 w-50 mx-auto ">
		<div class= "border p-5 mb-5">
			<h2>Rechercher un produit</h2>
			{# !searchbar form search by name #}
			{{ form(form) }}
				{# !searchbar form search by ref #}
				{{ form(form_ref)}}
					{# !searchbar form search by cat #}
					{{ form(form_cat) }}
						{% if resultats is not empty and resultats != 'null' %}
							<div class="text-center">
								<h3 class="text-info mx-auto">Résultat de recherche :</h3>
							</div>
							<div class="container d-flex justify-content-center w-100 mx-auto shadow border-primary p-3 gap-3 ">
								{% for resultat in resultats %}
									<div class="card" style="width: 25rem;">
										<img src="{{ asset('img/' ~ resultat.imageProduit) }}" class="card-img-top" alt="..." width="25%">
										<div class="card-body">
											<h4 class="card-title">{{ resultat.nomProduit }}</h4>
											<p class="card-text">Description:
												{{ resultat.descriptionProduit }}</p>
											<p class="card-text">
												Réf.<b>{{ resultat.reference.numeroReference }}</b>&nbsp&nbsp
												Cat.<b>{{resultat.category.nomCategory}}</b>
											</p>
										</div>

										<ul class="list-group list-group-flush">
											<li class="list-group-item">Prix:
												{{ resultat.prixProduit }}
												€</li>
											<li class="list-group-item">En stock:
												{{ resultat.stockProduit ? 'disponible' : 'rupture de stock' }}</li>
											<li class="list-group-item">Date de dépôt:
												{{ resultat.dateDepotProduit ? resultat.dateDepotProduit|date('d/m/Y') : '' }}</li>
										</ul>
										
										<div></div>
										<a class="btn btn-outline-success" href="{{ path('app_produits_show', {'id': resultat.id}) }}">Voir le produit</a>
									</div>
								{% endfor %}
							</div>
						{% elseif resultats  %}
							<div class="alert alert-danger">Aucun résultat pour cette recherche</div>
						{% endif %}


	<section class="d-flex justify-content-around align-items-baseline mt-5 mb-3 w-100 mx-auto ">
		<div>
			<h4>Références</h4>
			{% for reference in references %}
				<li class="list-group-item">
					<a href="{{ path('app_search_byRef', {'id': reference.id }) }}">{{reference.numeroReference}}</a>
				</li>
			{% endfor %}
		</div>

		<div>
			<h4>Catégories</h4>
			{% for category in categories %}
				<li class="list-group-item">
					<a href="{{ path('app_search_byCat', {'id': category.id }) }}">{{category.nomCategory}}</a>
				</li>
			{% endfor %}
		</div>

		<div>
			<h4>Enseignes</h4>
			{% for enseigne in enseignes %}
				<li class="list-group-item">
					<a href="{{ path('app_search_by_shop', {'id': enseigne.id }) }}">{{enseigne.nomEnseigne}}</a>
				</li>
			{% endfor %}
		</div>
	</section>
{% endblock %}