src/Entity/Enseignes.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\EnseignesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EnseignesRepository::class)]
#[ApiResource]
class Enseignes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_enseigne = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $nbre_employes = null;

    #[ORM\Column]
    private ?float $chiffre_affaire_annuel_HT = null;
    //! MANY TO MANY avec Produits
    #[ORM\ManyToMany(targetEntity: Produits::class, mappedBy: 'enseignes')]
    private Collection $produits;
    //tableau d'objet qui inclut un tableau en value json_encode

    public function __toString()
    {
        return $this->nom_enseigne;
    }

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEnseigne(): ?string
    {
        return $this->nom_enseigne;
    }

    public function setNomEnseigne(string $nom_enseigne): static
    {
        $this->nom_enseigne = $nom_enseigne;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getNbreEmployes(): ?int
    {
        return $this->nbre_employes;
    }

    public function setNbreEmployes(int $nbre_employes): static
    {
        $this->nbre_employes = $nbre_employes;

        return $this;
    }

    public function getChiffreAffaireAnnuelHT(): ?float
    {
        return $this->chiffre_affaire_annuel_HT;
    }

    public function setChiffreAffaireAnnuelHT(float $chiffre_affaire_annuel_HT): static
    {
        $this->chiffre_affaire_annuel_HT = $chiffre_affaire_annuel_HT;

        return $this;
    }

    /**
     * @return Collection<int, Produits>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produits $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->addEnseigne($this);
        }

        return $this;
    }

    public function removeProduit(Produits $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            $produit->removeEnseigne($this);
        }

        return $this;
    }
}

src/Form/EnseignesType.php
<?php

namespace App\Form;

use App\Entity\Enseignes;
use Doctrine\DBAL\Types\StringType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnseignesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_enseigne', TextType::class)
            ->add('ville', TextType::class)
            ->add('nbre_employes', NumberType::class)
            ->add('chiffre_affaire_annuel_HT', NumberType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Enseignes::class,
        ]);
    }
}

src/Controller/EnseignesController.php
<?php

namespace App\Controller;

use App\Entity\Enseignes;
use App\Form\EnseignesType;
use App\Repository\EnseignesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/enseignes')]
class EnseignesController extends AbstractController
{
    #[Route('/', name: 'app_enseignes_index', methods: ['GET'])]
    public function index(EnseignesRepository $enseignesRepository): Response
    {
        return $this->render('enseignes/index.html.twig', [
            'enseignes' => $enseignesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_enseignes_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $enseigne = new Enseignes();
        $form = $this->createForm(EnseignesType::class, $enseigne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($enseigne);
            $entityManager->flush();

            return $this->redirectToRoute('app_enseignes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('enseignes/new.html.twig', [
            'enseigne' => $enseigne,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_enseignes_show', methods: ['GET'])]
    public function show(Enseignes $enseigne): Response
    {
        return $this->render('enseignes/show.html.twig', [
            'enseigne' => $enseigne,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_enseignes_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Enseignes $enseigne, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EnseignesType::class, $enseigne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_enseignes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('enseignes/edit.html.twig', [
            'enseigne' => $enseigne,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_enseignes_delete', methods: ['POST'])]
    public function delete(Request $request, Enseignes $enseigne, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$enseigne->getId(), $request->request->get('_token'))) {
            $entityManager->remove($enseigne);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_enseignes_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/enseignes/_delete_form.html.twig
<form method="post" action="{{ path('app_enseignes_delete', {'id': enseigne.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ enseigne.id) }}">
    <button class="btn">Delete</button>
</form>

templates/enseignes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/enseignes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Enseignes{% endblock %}

{% block body %}
    <h1>Edit Enseignes</h1>

    {{ include('enseignes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_enseignes_index') }}">back to list</a>

    {{ include('enseignes/_delete_form.html.twig') }}
{% endblock %}

templates/enseignes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enseignes index
{% endblock %}

{% block body %}
	<h1>Enseignes</h1>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th>Id</th>
				<th>Nom enseigne</th>
				<th>Ville</th>
				<th>Nbre employes</th>
				<th>Chiffre d'affaire annuel HT</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for enseigne in enseignes %}
				<tr>
					<td>{{ enseigne.id }}</td>
					<td>{{ enseigne.nomEnseigne }}</td>
					<td>{{ enseigne.ville }}</td>
					<td>{{ enseigne.nbreEmployes }}</td>
					<td>{{ enseigne.chiffreAffaireAnnuelHT }} K€</td>
					<td>
						<a class= "btn btn-success" href="{{ path('app_enseignes_show', {'id': enseigne.id}) }}">show</a>
						<a class= "btn btn-primary" href="{{ path('app_enseignes_edit', {'id': enseigne.id}) }}">edit</a>
					</td>

				</tr>
			{% else %}
				<tr>
					<td colspan="6">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% if app.user %}
		<a href="{{ path('app_enseignes_new') }}">Create new</a>
	{% endif %}
{% endblock %}

templates/enseignes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une Enseigne{% endblock %}

{% block body %}
    <h1>Ajouter une Enseigne</h1>

    {{ include('enseignes/_form.html.twig') }}

    <a href="{{ path('app_enseignes_index') }}">retour à la liste des Enseignes</a>
{% endblock %}

templates/enseignes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enseignes{% endblock %}

{% block body %}
    <h1>Enseignes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ enseigne.id }}</td>
            </tr>
            <tr>
                <th>Nom_enseigne</th>
                <td>{{ enseigne.nomEnseigne }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ enseigne.ville }}</td>
            </tr>
            <tr>
                <th>Nbre_employes</th>
                <td>{{ enseigne.nbreEmployes }}</td>
            </tr>
            <tr>
                <th>Chiffre_affaire_annuel_HT</th>
                <td>{{ enseigne.chiffreAffaireAnnuelHT }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_enseignes_index') }}">back to list</a>

    <a href="{{ path('app_enseignes_edit', {'id': enseigne.id}) }}">edit</a>

    {{ include('enseignes/_delete_form.html.twig') }}
{% endblock %}