src/Entity/Clients.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ClientsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientsRepository::class)]
#[ApiResource]
class Clients
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_client = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom_client = null;

    #[ORM\Column(length: 255)]
    private ?string $mail_client = null;

    #[ORM\Column(length: 255)]
    private ?string $ville_client = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomClient(): ?string
    {
        return $this->nom_client;
    }

    public function setNomClient(string $nom_client): static
    {
        $this->nom_client = $nom_client;

        return $this;
    }

    public function getPrenomClient(): ?string
    {
        return $this->prenom_client;
    }

    public function setPrenomClient(string $prenom_client): static
    {
        $this->prenom_client = $prenom_client;

        return $this;
    }

    public function getMailClient(): ?string
    {
        return $this->mail_client;
    }

    public function setMailClient(string $mail_client): static
    {
        $this->mail_client = $mail_client;

        return $this;
    }

    public function getVilleClient(): ?string
    {
        return $this->ville_client;
    }

    public function setVilleClient(string $ville_client): static
    {
        $this->ville_client = $ville_client;

        return $this;
    }
}

src/Form/ClientsType.php
<?php

namespace App\Form;

use App\Entity\Clients;
use Doctrine\DBAL\Types\StringType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_client', TextType::class)
            ->add('prenom_client', TextType::class)
            ->add('mail_client', TextType::class)
            ->add('ville_client', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Clients::class,
        ]);
    }
}

src/Controller/ClientsController.php
<?php

namespace App\Controller;

use App\Entity\Clients;
use App\Form\ClientsType;
use App\Form\ClientType;
use App\Repository\ClientsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\ParameterBag;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/clients')]
class ClientsController extends AbstractController
{
    #[Route('/', name: 'app_clients')]
    public function index(): Response
    {
        return $this->render('clients/index.html.twig', [
            'controller_name' => 'ClientsController',
        ]);
    }
    
    #[Route('/all', name: 'app_clients_all', methods:['GET'])]
    public function displayAll(ClientsRepository $clientsRepository): Response
    //! injection de dépendances :abstraction de la classe ClientsRepository en la stockant dans une variable
    {
        return $this->render('clients/clients.html.twig', [
          'clients' => $clientsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_clients_new', methods:['GET','POST'])]
    public function addClient(Request $request, EntityManagerInterface $entityManagerInterface ): Response
    //! injection de dépendances :abstraction de la class Request pour prototypage de HEADER du BODY... ($_SERVER, $_SESSION, $_GET, $_POST, $_FILE...) équivalent encodeJson? et de la class EntityManagerInterface (dossier orm -> dossier lib\Doctrine\ORM-> fichier EntityManagerInterfac) pour accès aux méthodes de prototypage pour UPDATE et DELETE 
    {
        // echo $request->getPathInfo();///clients/new
        // echo $request->getUri();//http://127.0.0.1:8000/clients/new
        // echo $request->getUriForPath('/clients/new');//http://127.0.0.1:8000/clients/new
        // echo $request->headers->get('User-Agent');//Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
        
        $newClient= new Clients();
        // todo Instance de la classe Produit Entity
        $form= $this->createForm(ClientsType::class, $newClient);
        // todo methode createForm qui SERT A LIER un form à une entité. Prend comme parametre la class du formulaire et l'objet Entity créé ligne 45
        $form->handleRequest($request);
        
        // todo methode handleRequest() prototypé dans la class Request, récupère tous les champs du formaulaire
        //todo handleRequest($request) == $_POST['tous les attributs name des inputs']

        if($form->isSubmitted() && $form->isValid()){
            //todo isSubmitted == isset() en php isValid() == !empty() en php
            $entityManagerInterface->persist($newClient);
            //todo persist($nom de la table/entité) insert les données dans l'entité $client (=new Client)
            $entityManagerInterface->flush();
            //todo execute l'insertion, met à jour les datas

            return $this->redirectToRoute('app_client_all', array(), Response::HTTP_SEE_OTHER);
        }
        return $this->render('clients/new.html.twig', [
            'client' => $newClient,
            'form' => $form,
        ]);
    }


    #[Route('/{id}', name: 'app_clients_show', methods:['GET'])]
    //!{id} équivaut à $_GET['id'] en PHP
    public function show(Clients $client): Response
    //! injection de dépendances :abstraction de la classe Clients (Entity) et la stocker dans variable pour avoir accès ici (sur le controller) à methode getId() de la classe CLients
    {
        return $this->render('clients/show.html.twig', [
            'client' => $client,
        ]);
        
    }

    #[Route('/{id}/edit', name: 'app_clients_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Clients $client, EntityManagerInterface $entityManagerInterface):Response
    {
        $form= $this->createForm(ClientsType::class, $client);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $entityManagerInterface->flush();

            return $this->redirectToRoute('app_clients_all', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('clients/edit.html.twig', [
            'client'=>$client,
            'form'=>$form,
        ]);
    }

    #[Route('/{id}', name: 'app_clients_delete', methods: ['POST'])]
    public function delete(Request $request, Clients $client, EntityManagerInterface $entityManagerInterface):Response
    {
        if($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))){
            $entityManagerInterface->remove($client);
            $entityManagerInterface->flush();
        }
        return $this->redirectToRoute('app_clients_all', [], Response::HTTP_SEE_OTHER);
    }


}

templates/clients/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/clients/clients.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de tous les clients
{% endblock %}

{% block body %}

	<h2>Clients</h2>
	<div class="row m-auto text-align-center">
		<table class="table table-striped table-hover">
			<thead class="table-dark">
				<tr>
					<th scope="col" class="produit-size">ID</th>
					<th scope="col" class="produit-size">Nom</th>
					<th scope="col" class="produit-size">Prenom</th>
					<th scope="col" class="produit-size">E-mail</th>
					<th scope="col" class="produit-size">Ville</th>
					<th scope="col" class="produit-size">Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for client in clients %}
					<tr>
						<td class="produit-size">{{client.id}}</td>
						{# !.id car ici c'est la méthode getId() qui est appellé (public function getPrenomClient() ds Entity/Clients.php) #}
						<td class="produit-size">{{client.nomClient}}</td>
						{# !.nomClient au lieu de nom de colonne nom_client car ici c'est la méthode getPrenomClient() qui est appellé (public function getPrenomClient() ds Entity/Clients.php) #}
						<td class="produit-size">{{client.prenomClient}}</td>
						<td class="produit-size">{{client.mailClient}}</td>
						<td class="produit-size">{{client.villeClient}}</td>

						<td>
							<button style="background-color: brown">
								<a href="{{path('app_clients_new')}}" style="text-decoration: none; color: white; ">Ajouter client</a>
							</button>
							<button style="background-color: brown">
								<a href="{{path('app_clients_show', {'id': client.id})}}" style="text-decoration: none; color: white; ">Infos client</a>
							</button>
							<button style="background-color: brown">
								<a href="{{ path('app_clients_edit', {'id': client.id}) }}" style="text-decoration: none; color: white; ">edit</a>
							</button>
						</td>
					</tr>

				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/clients/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientsController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/ACS/my_project/src/Controller/ClientsController.php'|file_link(0) }}">src/Controller/ClientsController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/ACS/my_project/templates/clients/index.html.twig'|file_link(0) }}">templates/clients/index.html.twig</a></code></li>
    </ul>
</div>

<div class="wrapper_button">
<button>
<a href="{{path('app_clients_all')}}">Affiche tous les Clients</a>
</button>
</div>
{% endblock %}

templates/clients/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau client{% endblock %}

{% block body %}
    <h1>Ajouter un nouveau client</h1>

    {{ include('clients/_form.html.twig') }}

    <a href="{{ path('app_clients_all') }}">retour liste de tous les clients</a>
{% endblock %}

templates/clients/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Informations d'un Client{% endblock %}

{% block body %}
    <h1>Informations d'un client</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ client.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ client.nomClient }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ client.prenomClient}}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ client.mailClient}}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ client.villeClient}}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_clients_all') }}">retour à la liste</a>

    {# <a href="{{ path('app_clients_edit', {'id': client.id}) }}">edit</a> #}

    {# {{ include('clients/_delete_form.html.twig') }} #}
{% endblock %}